"""empty message

Revision ID: f353b1660f9b
Revises: 
Create Date: 2026-04-30 17:14:56.779161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f353b1660f9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('comentario_usuario_id'), table_name='comentario')
    op.drop_index(op.f('comentario_video_id'), table_name='comentario')
    op.drop_table('comentario')
    op.drop_index(op.f('reproduccion_usuario_id'), table_name='reproduccion')
    op.drop_index(op.f('reproduccion_video_id'), table_name='reproduccion')
    op.drop_table('reproduccion')
    op.drop_index(op.f('suscripcion_creador_id'), table_name='suscripcion')
    op.drop_index(op.f('suscripcion_suscriptor_id'), table_name='suscripcion')
    op.drop_index(op.f('suscripcion_suscriptor_id_creador_id_uniq'), table_name='suscripcion')
    op.drop_table('suscripcion')
    op.alter_column('usuario', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('usuario_correo_key'), table_name='usuario')
    op.drop_index(op.f('usuario_correo_like'), table_name='usuario')
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=False)
    op.alter_column('video', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('video', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('video', 'titulo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('video', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('video', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('video', 'duracion',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('video', 'creador_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.drop_index(op.f('video_creador_id'), table_name='video')
    op.drop_index(op.f('video_uuid_key'), table_name='video')
    op.create_index(op.f('ix_video_titulo'), 'video', ['titulo'], unique=False)
    op.create_index(op.f('ix_video_uuid'), 'video', ['uuid'], unique=False)
    op.drop_constraint(op.f('video_creador_id_fkey'), 'video', type_='foreignkey')
    op.create_foreign_key(None, 'video', 'usuario', ['creador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.create_foreign_key(op.f('video_creador_id_fkey'), 'video', 'usuario', ['creador_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_index(op.f('ix_video_uuid'), table_name='video')
    op.drop_index(op.f('ix_video_titulo'), table_name='video')
    op.create_index(op.f('video_uuid_key'), 'video', ['uuid'], unique=True)
    op.create_index(op.f('video_creador_id'), 'video', ['creador_id'], unique=False)
    op.alter_column('video', 'creador_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('video', 'duracion',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=False)
    op.alter_column('video', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('video', 'descripcion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('video', 'titulo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('video', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('video', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.create_index(op.f('usuario_correo_like'), 'usuario', ['correo'], unique=False)
    op.create_index(op.f('usuario_correo_key'), 'usuario', ['correo'], unique=True)
    op.alter_column('usuario', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('suscripcion',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('creador_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('suscriptor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuario.id'], name=op.f('suscripcion_creador_id_fkey'), onupdate='RESTRICT', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suscriptor_id'], ['usuario.id'], name=op.f('suscripcion_suscriptor_id_fkey'), onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('suscripcion_pkey'))
    )
    op.create_index(op.f('suscripcion_suscriptor_id_creador_id_uniq'), 'suscripcion', ['suscriptor_id', 'creador_id'], unique=True)
    op.create_index(op.f('suscripcion_suscriptor_id'), 'suscripcion', ['suscriptor_id'], unique=False)
    op.create_index(op.f('suscripcion_creador_id'), 'suscripcion', ['creador_id'], unique=False)
    op.create_table('reproduccion',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('fecha_reproduccion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('dispositivo_reproduccion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('reproduccion_usuario_id_fkey'), onupdate='RESTRICT', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('reproduccion_video_id_fkey'), onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reproduccion_pkey'))
    )
    op.create_index(op.f('reproduccion_video_id'), 'reproduccion', ['video_id'], unique=False)
    op.create_index(op.f('reproduccion_usuario_id'), 'reproduccion', ['usuario_id'], unique=False)
    op.create_table('comentario',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('comentario_usuario_id_fkey'), onupdate='RESTRICT', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('comentario_video_id_fkey'), onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('comentario_pkey'))
    )
    op.create_index(op.f('comentario_video_id'), 'comentario', ['video_id'], unique=False)
    op.create_index(op.f('comentario_usuario_id'), 'comentario', ['usuario_id'], unique=False)
    # ### end Alembic commands ###
