"""creating_table_country

Revision ID: eed0a8914709
Revises: 500fc28376d2
Create Date: 2026-04-30 17:37:44.108017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed0a8914709'
down_revision: Union[str, Sequence[str], None] = '500fc28376d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pais_pkey')
    )
    op.create_index('pais_nombre_key', 'pais', ['nombre'], unique=True)
    op.bulk_insert(
        sa.table('pais', sa.column('id', sa.BigInteger), sa.column('nombre', sa.String)),
        [
            {'id': 1, 'nombre': 'México'},
            {'id': 2, 'nombre': 'Estados Unidos'},
            {'id': 3, 'nombre': 'Canadá'},
            {'id': 4, 'nombre': 'Argentina'},
            {'id': 5, 'nombre': 'Colombia'},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('pais_nombre_key', table_name='pais')
    op.drop_table('pais')
    # ### end Alembic commands ###
